This is homework assignment #1. Please use this file to write code and submit separate file with answers provided.

1 Set $X = \sqrt{17}$ rounded to the nearest digit. Print the message using the variable "Approximate square root of 17 is X". Where X is the variable.

In [1]:
import math
X = round(math.sqrt(17))
print("Approximate square root of 17 is %d" %X)

Approximate square root of 17 is 4


2 Covert all words to lowcase and drop all numbers and punctiation from the string.
S = "(1) An official wants to multiply subordinates, not rivals and (2) Officials make work for each other. [Parkinson] notes in particular that the total of those employed inside a bureaucracy rose by 5-7% per year irrespective of any variation in the amount of work (if any) to be done.”

In [2]:
S = "(1) An official wants to multiply subordinates, not rivals and (2) Officials make work for each other. [Parkinson] notes in particular that the total of those employed inside a bureaucracy rose by 5-7% per year irrespective of any variation in the amount of work (if any) to be done." 
S1 = S.lower()
S2 = filter(str.isalpha,S1)
print(''.join(list(S2)))

anofficialwantstomultiplysubordinatesnotrivalsandofficialsmakeworkforeachotherparkinsonnotesinparticularthatthetotalofthoseemployedinsideabureaucracyrosebyperyearirrespectiveofanyvariationintheamountofworkifanytobedone


3 Create a list of vegetables : carrot, potato, tomato, cabbage. Extract the first and last vegetable into another list. 

In [3]:
x = ['carrot', 'potato', 'tomato', 'cabbage']
y = [x[0],x[3]]
#y = [x[0], x[3]]
x.pop(0)
#del(x[0])
x.pop()
#del(x[2])
print(x,y)

['potato', 'tomato'] ['carrot', 'cabbage']


4  Create a vector from 0 to 9, extract elements on positions 2-4, and  on positions 7-9 into a another vector     

In [4]:
import numpy as np
x = np.array(range(0,10))
print(x)
y1 = list(x[1:4])
y2 = list(x[6:9])
print(y1,y2)
y = np.array(y1+y2)
# Y = np.concatenate([y1,y2])
print(type(y))
print(y)

[0 1 2 3 4 5 6 7 8 9]
[1, 2, 3] [6, 7, 8]
<class 'numpy.ndarray'>
[1 2 3 6 7 8]


5 Create a vector of squared number from 3 to 13 using a loop, extract the smallest, the largest number and the lenght of the vector.

In [5]:
import numpy as np
x = list(range(3,14))
y = []
for i in x:
    y.append(np.square(i))
print(y)
z = np.array(y)
print(min(z),max(z),len(z))    

[9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169]
9 169 11


6 Create a vector from  2 to 13, and a vector from 56 to 59. Then insert the second list in the position 5 of the first.

In [6]:
x = list(range(2,14))
y = list(range(56,60))
print(x,y)
x.insert(5,y)
print(x)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] [56, 57, 58, 59]
[2, 3, 4, 5, 6, [56, 57, 58, 59], 7, 8, 9, 10, 11, 12, 13]


7 Loop over the number from 17 to 36. Set up a condition under which you print the current looping number and print if it is even or odd.

In [7]:
x = 0
for i in range(17,37):
    x += 1
    print("current looping number:", x)
    if i%2==0:
        print("{0} is even".format(i))
    else:
        print("{0} is odd".format(i))

current looping number: 1
17 is odd
current looping number: 2
18 is even
current looping number: 3
19 is odd
current looping number: 4
20 is even
current looping number: 5
21 is odd
current looping number: 6
22 is even
current looping number: 7
23 is odd
current looping number: 8
24 is even
current looping number: 9
25 is odd
current looping number: 10
26 is even
current looping number: 11
27 is odd
current looping number: 12
28 is even
current looping number: 13
29 is odd
current looping number: 14
30 is even
current looping number: 15
31 is odd
current looping number: 16
32 is even
current looping number: 17
33 is odd
current looping number: 18
34 is even
current looping number: 19
35 is odd
current looping number: 20
36 is even


8 Create a function that transforms an argument. First is takes a square root of the argument, then it adds 5, finally divides it by 7. Run the example with argument x = 5

In [8]:
y = lambda x: (math.sqrt(x) + 5)/7
y(5)

1.0337239967856842

9 Create a 3x3 matrix with elements from 1 to 9 and add a row to the bottom of the matrix with number 11 13 15. 

In [9]:
x = np.array(range(1,10))
x = x.reshape(3,3)
y = np.array([11,13,15])
print(x,y)
z = np.insert(x,[3],y,axis=0)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [11 13 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 13 15]]
